import {AddressSheetsNew} from './addressSheetNew';
import {AddressSheetsNewIOS} from './addressSheetNewIOS';
import {BanksSheet} from './BanksSheet';
import {ComplaintSheet} from './complaintSheet';
import {ContractTypeSheet} from './contractType';
import {Earnings} from './earnings';
import {EarningsOrderSheet} from './earningsOrderSheet';
import {GuarantorFormSheet} from './guarantorFormSheet';
import {OrderDetailsSheet} from './orderDetails';
import {OrderHelpSheet} from './orderHelp';
import {ProfileSheets} from './profileSheet';
import {RateCustomerSheet} from './rateCustomer';
import {SettingsSheet} from './settingsSheet';
import {VehicleDetailsSheet} from './vehicleDetailsSheet';
import {VerifyIdentitySheet} from './verifyIdentity';
import {WorkDurationSheet} from './WorkDurationSheet';
import {registerSheet} from 'react-native-actions-sheet';

registerSheet('profileSheet', ProfileSheets);
registerSheet('bankSheet', BanksSheet);
registerSheet('orderDetailsSheet', OrderDetailsSheet);
registerSheet('orderHelpSheet', OrderHelpSheet);
registerSheet('addressSheetNew', AddressSheetsNew);
registerSheet('addressSheetNewIOS', AddressSheetsNewIOS);
registerSheet('verifyIdentitySheet', VerifyIdentitySheet);
registerSheet('settingsSheet', SettingsSheet);
registerSheet('contractType', ContractTypeSheet);
registerSheet('rateCustomerSheet', RateCustomerSheet);
registerSheet('EarningsSheet', Earnings);
registerSheet('EarningsOrderSheet', EarningsOrderSheet);
registerSheet('ComplaintSheet', ComplaintSheet);
registerSheet('GuarantorFormSheet', GuarantorFormSheet);
registerSheet('WorkDurationSheet', WorkDurationSheet);
registerSheet('VehicleDetailsSheet', VehicleDetailsSheet);
