name: CI Trigger Bitrise

on:
  push:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Step
        run: echo "Test not added yet"

  bitrise-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Determine Tier
        id: tier
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "TIER=main" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "TIER=dev" >> $GITHUB_ENV
          else
            echo "TIER=staging" >> $GITHUB_ENV
          fi

      - name: Trigger Bitrise Build
        env:
          BITRISE_APP_SLUG: ${{ secrets.BITRISE_APP_SLUG }}
          BITRISE_ACCESS_TOKEN: ${{ secrets.BITRISE_ACCESS_TOKEN }}
          BRANCH_NAME: ${{ github.ref_name }}
          COMMIT_HASH: ${{ github.sha }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          TIER: ${{ env.TIER }}
        run: |
          # Clean commit message for JSON
          CLEAN_MSG=$(echo "$COMMIT_MESSAGE" | tr -d '\n\r' | sed 's/"/\\"/g' | head -c 200)

          for PLATFORM in ios; do
            WORKFLOW_ID="primary-$PLATFORM"
            echo "Triggering Bitrise build for $PLATFORM..."
            
            curl -X POST "https://app.bitrise.io/app/$BITRISE_APP_SLUG/build/start.json" \
              -H "Authorization: $BITRISE_ACCESS_TOKEN" \
              -H "Content-Type: application/json" \
              --fail-with-body \
              -d "{
                \"hook_info\": {
                  \"type\": \"bitrise\"
                },
                \"build_params\": {
                  \"workflow_id\": \"$WORKFLOW_ID\",
                  \"branch\": \"$BRANCH_NAME\",
                  \"commit_hash\": \"$COMMIT_HASH\",
                  \"commit_message\": \"$CLEAN_MSG\",
                  \"environments\": [
                    {
                      \"mapped_to\": \"TIER\",
                      \"value\": \"$TIER\",
                      \"is_expand\": true
                    }
                  ]
                },
                \"triggered_by\": \"GitHub Actions\"
              }"
          done
